/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhao_apkcrack_ResUtils_ELF_Elf */

#ifndef _Included_zhao_apkcrack_ResUtils_ELF_Elf
#define _Included_zhao_apkcrack_ResUtils_ELF_Elf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhao_apkcrack_ResUtils_ELF_Elf
 * Method:    ELFHash
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_zhao_apkcrack_ResUtils_ELF_Elf_ELFHash
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
